{\rtf1\ansi\ansicpg1252\cocoartf2868
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red119\green61\blue243;\red245\green245\blue245;\red14\green16\blue19;
\red253\green154\blue15;\red218\green109\blue27;\red89\green152\blue85;}
{\*\expandedcolortbl;;\cssrgb\c54510\c36078\c96471;\cssrgb\c96863\c96863\c96863;\cssrgb\c6667\c7843\c9412;
\cssrgb\c100000\c66667\c5098;\cssrgb\c89020\c50588\c13333;\cssrgb\c41569\c65098\c40784;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs28 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 FROM\cf4 \cb3 \strokec4  python:\cf5 \cb3 \strokec5 3.11\cf4 \cb3 \strokec4 -slim\
\
\pard\pardeftab720\partightenfactor0
\cf6 \cb3 \strokec6 # Install FFmpeg\cf4 \cb3 \strokec4 \
\pard\pardeftab720\partightenfactor0
\cf2 \cb3 \strokec2 RUN\cf4 \cb3 \strokec4  apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*\
\
\cf2 \cb3 \strokec2 WORKDIR\cf4 \cb3 \strokec4  /app\
\cf2 \cb3 \strokec2 COPY\cf4 \cb3 \strokec4  requirements.txt .\
\cf2 \cb3 \strokec2 RUN\cf4 \cb3 \strokec4  pip install --no-cache-dir -r requirements.txt\
\
\cf2 \cb3 \strokec2 COPY\cf4 \cb3 \strokec4  . .\
\
\cf2 \cb3 \strokec2 EXPOSE\cf4 \cb3 \strokec4  \cf5 \cb3 \strokec5 8000\cf4 \cb3 \strokec4 \
\cf2 \cb3 \strokec2 CMD\cf4 \cb3 \strokec4  [\cf7 \cb3 \strokec7 "uvicorn"\cf4 \cb3 \strokec4 , \cf7 \cb3 \strokec7 "main:app"\cf4 \cb3 \strokec4 , \cf7 \cb3 \strokec7 "--host"\cf4 \cb3 \strokec4 , \cf7 \cb3 \strokec7 "0.0.0.0"\cf4 \cb3 \strokec4 , \cf7 \cb3 \strokec7 "--port"\cf4 \cb3 \strokec4 , \cf7 \cb3 \strokec7 "8000"\cf4 \cb3 \strokec4 ]}